# Generated by Django 5.1.3 on 2025-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='报餐人')),
                ('date', models.DateTimeField(verbose_name='报餐时间')),
                ('breakfast', models.BooleanField(blank=True, null=True)),
                ('lunch', models.BooleanField(blank=True, null=True)),
                ('dinner', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '报餐详情表',
            },
        ),
    ]
