# Generated by Django 5.1.3 on 2025-04-13 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='breakfast',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='date',
            field=models.DateField(verbose_name='报餐时间'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='dinner',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='lunch',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('date', 'name')},
        ),
    ]
