# Generated by Django 5.1.3 on 2025-04-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdemo', '0002_orderdetail_created_at_orderdetail_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
