# Generated by Django 5.1.3 on 2025-04-13 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdemo', '0003_userlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlist',
            options={'verbose_name_plural': '成员表'},
        ),
    ]
